stages:
  - build
  - test

build:
  stage: build
  script:
    - "mkdir cmake-build-debug"
    - "cd cmake-build-debug"
    - "cmake .."
    - "cmake --build . --target common"

test:
  stage: test
  dependencies:
    - build
  script:
    - "mkdir cmake-build-debug"
    - "cd cmake-build-debug"
    - "cmake .."
    - "cmake --build . --target unittest_common"
    - "./code/common/unittest_common -r junit -o results_common.xml"
  artifacts:
    reports:
      junit:
        - cmake-build-debug/code/common/results_common.xml
