stages:
  - build
  - test

build:
  stage: build
  script:
    - "mkdir cmake-build-debug"
    - "cd cmake-build-debug"
    - "cmake .."
    - "cmake --build . --target common"
    - "cmake --build . --target unittest_common"

test:
  stage: test
  dependencies:
    - build
  script:
    - "cd cmake-build_debug"
    - "./unittest_common"
