#line 2 "code/game/bg_lex.yy.c"
#line 2 "code/game/bg_lex.lex"
#include "q_shared.h"
#include "bg_lex.h"

#define YY_FATAL_ERROR(msg) bgLexFatalError(msg, yyscanner)
#define UNUSED(x) ((void)(x))



#line 12 "code/game/bg_lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 64
#define YY_END_OF_BUFFER 65
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[308] =
    {   0,
        0,    0,   65,   63,   61,   62,   63,   55,   56,   63,
       60,    2,   59,    4,   57,   58,   53,   54,    0,    1,
        2,    3,    2,    4,    4,    0,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    5,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    6,    0,    0,    7,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    0,    0,    0,
        0,    0,    0,    0,    0,   21,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    8,   13,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   10,    0,    0,   11,    0,    0,    0,    0,    0,
        0,    0,    0,   22,   23,    0,    0,   25,    0,    0,
        0,    0,    0,    0,    0,   14,    0,   15,    0,    0,
        0,    0,   29,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   12,   17,    0,    0,    0,    0,    0,

        0,    0,    0,   24,   26,   27,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   16,    0,   30,   31,    0,
        0,   33,    0,    0,    0,    0,    0,    0,    0,   18,
        0,   19,    0,    0,    0,    0,   28,   37,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   32,   34,
       35,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       20,    0,   38,   39,    0,    0,   41,    0,    0,    0,
        0,    0,   36,   45,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   40,   42,   43,    0,    0,   46,
       47,    0,    0,   49,    0,    0,    0,    0,    0,   44,

       48,   50,   51,    0,    0,   52,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    1,    6,
        7,    1,    1,    8,    9,   10,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,   12,    1,
        1,    1,    1,    1,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       14,    1,   15,    1,    1,    1,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   16,    1,   17,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[18] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[309] =
    {   0,
        0,    0,  364,  703,  703,  703,  358,  703,  703,  350,
      703,    8,  703,    9,  703,  703,  355,  703,  353,  703,
       13,  346,   15,   16,   17,   27,  345,  341,   35,   43,
      347,   51,    0,  339,   59,   67,   23,  345,    0,   75,
       29,    0,  337,   83,  333,   91,   99,  331,  107,  115,
       31,   33,  337,  123,    0,  131,   45,    0,  329,  139,
      147,   46,    0,  326,  161,  169,   40,  332,    0,  323,
      177,  185,   49,   57,  329,  193,    0,  321,  201,  703,
      209,   62,  223,   63,    0,  318,  237,  245,  253,   64,
        0,  317,  267,  275,   73,  323,    0,   68,   78,    0,

      315,  283,  703,  314,  291,  703,  299,   79,  313,  320,
      327,    0,  312,  335,  311,  343,  703,  351,   88,  365,
       93,    0,  309,  379,  387,  703,   92,   94,   96,  103,
        0,  108,  111,    0,  308,  395,  703,  703,  403,  411,
      314,    0,  425,  311,  439,    0,  112,  117,    0,  303,
      447,  703,  300,  455,  703,  463,  119,  477,  305,  491,
        0,  296,  499,  703,  703,  116,  128,  703,  137,  133,
      142,  134,    0,  295,  507,  703,  515,  703,  523,  531,
      277,    0,  703,  144,  149,  151,  158,    0,  153,  163,
        0,  252,  545,  703,  703,  553,  561,  217,    0,  575,

      188,  589,    0,  703,  703,  703,  159,  171,  162,  173,
        0,  180,  597,  141,  605,  703,  613,  703,  703,  181,
      179,  703,  182,  189,  191,  198,    0,  125,  621,  703,
      629,  703,  637,  645,  102,    0,  703,  703,  199,  203,
      202,  206,    0,  211,  218,    0,   77,  659,  703,  703,
      703,  219,  220,  221,  226,    0,   69,  667,   53,  675,
      703,  683,  703,  703,  229,  231,  703,  235,  239,  249,
      240,    0,  703,  703,  251,  254,  255,  256,    0,  257,
      265,    0,   47,  691,  703,  703,  703,  271,  269,  703,
      703,  279,  278,  703,  281,  286,  287,  288,    0,  703,

      703,  703,  703,  296,  301,  703,  703,   20
    } ;

static yyconst flex_int16_t yy_def[309] =
    {   0,
      307,    1,  307,  307,  307,  307,  308,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  308,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,   29,  307,  307,  307,   32,  307,   32,  307,
      307,   35,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,   44,  307,  307,   46,  307,  307,
      307,  307,   49,  307,  307,  307,  307,  307,   54,  307,
      307,  307,  307,  307,  307,  307,   60,  307,  307,  307,
      307,  307,  307,  307,   65,  307,  307,  307,  307,  307,
       71,  307,  307,  307,  307,  307,   76,  307,  307,   79,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,   87,  307,  307,  307,  307,  307,  307,  307,  307,
      307,   93,  307,  307,  307,  307,  307,  307,  307,  307,
      102,  307,  307,  105,  307,  307,  307,  307,  307,  307,
      307,  111,  307,  307,  307,  114,  307,  307,  116,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      124,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  136,  307,  307,  307,  307,  307,  307,  307,
      307,  145,  307,  307,  307,  307,  307,  151,  307,  307,
      154,  307,  307,  307,  307,  307,  307,  307,  160,  307,

      307,  307,  163,  307,  307,  307,  307,  307,  307,  307,
      175,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  193,  307,  307,  307,
      307,  307,  307,  307,  307,  202,  307,  307,  307,  307,
      307,  307,  213,  307,  307,  215,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  229,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  248,  307,  307,  307,  307,  307,  307,  258,  307,
      307,  260,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  284,  307,

      307,  307,  307,  307,  307,  307,    0,  307
    } ;

static yyconst flex_int16_t yy_nxt[721] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    4,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   22,   23,   24,
       19,   25,   22,   23,   22,   23,   24,   24,   24,   25,
       26,   45,   50,   46,   50,   28,   52,   29,   30,   51,
       53,   51,   31,   67,   32,   33,   30,   68,   72,   81,
       31,   34,   72,   35,   37,   73,   82,  284,   38,   73,
       74,   39,   40,  260,   75,   81,  107,  118,   41,   42,
       36,   98,   82,  108,  119,   43,   95,   44,   40,  258,
       96,  127,  107,   48,  126,   49,   52,  248,  128,  108,
       53,  118,   54,   55,   56,  127,  156,  127,  119,  129,

       57,   58,   47,  157,  128,  262,  166,   59,  164,   60,
       61,  132,  165,  167,  169,  147,   62,   63,   50,  166,
      184,  170,  156,   64,  168,   65,   67,  185,  183,  157,
       68,  166,  204,   69,   56,  229,  169,  207,  167,   70,
      169,   71,   74,  170,  208,  171,   75,  184,   76,   77,
       61,  215,  184,  205,  186,   78,  189,   79,  206,  185,
      218,  220,  207,   80,   83,  209,  223,  219,  221,  222,
       84,   85,   66,  224,  207,  237,  239,   86,  238,   87,
       89,  208,  220,  240,  220,  223,   90,   91,   72,  221,
      213,  233,  223,   92,  225,   93,   95,  249,  250,  224,

       96,  252,  239,   97,   98,  241,  239,  251,  253,  265,
       99,  100,   81,  240,  244,  263,  266,  101,  264,  102,
      231,  268,  252,  252,  254,  103,   83,  267,  269,  275,
      253,  104,  265,  105,  265,  273,  276,  274,  268,  106,
      109,  266,  268,  288,  110,  285,  111,  112,   88,  269,
      289,  286,  270,  113,  275,  114,   89,  275,  277,  292,
      280,  115,  193,  116,  276,  287,  293,  290,  295,  117,
      120,  291,  288,  294,  288,  296,  121,  122,   94,  289,
      217,  292,  292,  123,  295,  124,  129,  300,  293,  295,
      297,  304,  130,  131,  132,  301,  296,  302,  305,  304,

      133,  134,  107,  303,  304,  175,  163,  135,  196,  136,
      154,  305,  306,  151,  179,  137,  109,  177,  136,  124,
      110,  116,  114,  139,  105,  102,  125,   93,   87,  138,
      140,   79,   94,   71,  141,   88,   65,  142,  143,   60,
       66,   49,  144,   46,  145,  146,  147,   44,   47,   35,
       36,   29,  148,  149,  118,   27,   27,   20,   26,  150,
       21,  151,   20,  307,  307,  307,  307,  152,  120,  307,
      307,  307,  307,  153,  307,  154,  307,  307,  307,  307,
      307,  155,  158,  307,  307,  307,  159,  307,  160,  161,
      125,  307,  307,  307,  307,  162,  307,  163,  171,  307,

      307,  307,  307,  307,  172,  173,  139,  307,  307,  307,
      307,  174,  307,  175,  140,  307,  307,  307,  141,  307,
      307,  307,  307,  307,  307,  307,  307,  176,  143,  307,
      307,  307,  144,  307,  307,  307,  307,  307,  307,  307,
      307,  178,  180,  307,  307,  307,  181,  307,  307,  182,
      186,  307,  307,  307,  307,  307,  187,  188,  189,  307,
      307,  307,  307,  307,  190,  191,  156,  307,  307,  307,
      307,  192,  307,  193,  307,  307,  307,  307,  307,  194,
      158,  307,  307,  307,  159,  307,  307,  307,  307,  307,
      307,  307,  307,  195,  197,  307,  307,  307,  198,  307,

      307,  199,  200,  307,  307,  307,  201,  307,  202,  203,
      209,  307,  307,  307,  307,  307,  210,  211,  177,  307,
      307,  307,  307,  212,  307,  213,  179,  307,  307,  307,
      307,  214,  307,  215,  180,  307,  307,  307,  181,  307,
      307,  307,  307,  307,  307,  307,  307,  216,  225,  307,
      307,  307,  307,  307,  226,  227,  196,  307,  307,  307,
      307,  228,  307,  229,  197,  307,  307,  307,  198,  307,
      307,  307,  307,  307,  307,  307,  307,  230,  200,  307,
      307,  307,  201,  307,  307,  307,  307,  307,  307,  307,
      307,  232,  234,  307,  307,  307,  235,  307,  307,  236,

      241,  307,  307,  307,  307,  307,  242,  243,  244,  307,
      307,  307,  307,  307,  245,  246,  217,  307,  307,  307,
      307,  247,  307,  248,  254,  307,  307,  307,  307,  307,
      255,  256,  231,  307,  307,  307,  307,  257,  307,  258,
      233,  307,  307,  307,  307,  259,  307,  260,  234,  307,
      307,  307,  235,  307,  307,  307,  307,  307,  307,  307,
      307,  261,  270,  307,  307,  307,  307,  307,  271,  272,
      277,  307,  307,  307,  307,  307,  278,  279,  280,  307,
      307,  307,  307,  307,  281,  282,  262,  307,  307,  307,
      307,  283,  307,  284,  297,  307,  307,  307,  307,  307,

      298,  299,    3,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307
    } ;

static yyconst flex_int16_t yy_chk[721] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   12,   12,   14,
      308,   14,   21,   21,   23,   23,   24,   25,   24,   25,
       26,   37,   41,   37,   51,   26,   52,   26,   29,   41,
       52,   51,   29,   67,   29,   29,   30,   67,   57,   62,
       30,   30,   73,   30,   32,   57,   62,  283,   32,   73,
       74,   32,   35,  259,   74,   82,   84,   90,   35,   35,
       36,   98,   82,   84,   90,   36,   95,   36,   40,  257,
       95,   99,  108,   40,   98,   40,   44,  247,   99,  108,
       44,  119,   44,   44,   46,  127,  121,  128,  119,  129,

       46,   46,   47,  121,  128,  235,  130,   47,  127,   47,
       49,  132,  129,  130,  133,  147,   49,   49,   50,  166,
      148,  133,  157,   50,  132,   50,   54,  148,  147,  157,
       54,  167,  166,   54,   56,  228,  170,  172,  167,   56,
      169,   56,   60,  170,  172,  171,   60,  184,   60,   60,
       61,  214,  185,  169,  186,   61,  189,   61,  171,  185,
      184,  187,  207,   61,   65,  209,  190,  186,  187,  189,
       65,   65,   66,  190,  208,  207,  210,   66,  209,   66,
       71,  208,  221,  210,  220,  223,   71,   71,   72,  221,
      212,  201,  224,   72,  225,   72,   76,  220,  223,  224,

       76,  226,  239,   76,   79,  241,  240,  225,  226,  242,
       79,   79,   81,  240,  244,  239,  242,   81,  241,   81,
      198,  245,  252,  253,  254,   81,   83,  244,  245,  255,
      253,   83,  265,   83,  266,  252,  255,  254,  268,   83,
       87,  266,  269,  271,   87,  265,   87,   87,   88,  269,
      271,  268,  270,   88,  275,   88,   89,  276,  277,  278,
      280,   89,  192,   89,  276,  270,  278,  275,  281,   89,
       93,  277,  289,  280,  288,  281,   93,   93,   94,  289,
      181,  293,  292,   94,  295,   94,  102,  288,  293,  296,
      297,  298,  102,  102,  105,  292,  296,  295,  298,  304,

      105,  105,  107,  297,  305,  174,  162,  107,  159,  107,
      153,  305,  304,  150,  144,  107,  109,  141,  135,  123,
      109,  115,  113,  110,  104,  101,   96,   92,   86,  109,
      111,   78,   75,   70,  111,   68,   64,  111,  114,   59,
       53,   48,  114,   45,  114,  114,  116,   43,   38,   34,
       31,   28,  116,  116,  118,   27,   22,   19,   17,  118,
       10,  118,    7,    3,    0,    0,    0,  118,  120,    0,
        0,    0,    0,  120,    0,  120,    0,    0,    0,    0,
        0,  120,  124,    0,    0,    0,  124,    0,  124,  124,
      125,    0,    0,    0,    0,  125,    0,  125,  136,    0,

        0,    0,    0,    0,  136,  136,  139,    0,    0,    0,
        0,  139,    0,  139,  140,    0,    0,    0,  140,    0,
        0,    0,    0,    0,    0,    0,    0,  140,  143,    0,
        0,    0,  143,    0,    0,    0,    0,    0,    0,    0,
        0,  143,  145,    0,    0,    0,  145,    0,    0,  145,
      151,    0,    0,    0,    0,    0,  151,  151,  154,    0,
        0,    0,    0,    0,  154,  154,  156,    0,    0,    0,
        0,  156,    0,  156,    0,    0,    0,    0,    0,  156,
      158,    0,    0,    0,  158,    0,    0,    0,    0,    0,
        0,    0,    0,  158,  160,    0,    0,    0,  160,    0,

        0,  160,  163,    0,    0,    0,  163,    0,  163,  163,
      175,    0,    0,    0,    0,    0,  175,  175,  177,    0,
        0,    0,    0,  177,    0,  177,  179,    0,    0,    0,
        0,  179,    0,  179,  180,    0,    0,    0,  180,    0,
        0,    0,    0,    0,    0,    0,    0,  180,  193,    0,
        0,    0,    0,    0,  193,  193,  196,    0,    0,    0,
        0,  196,    0,  196,  197,    0,    0,    0,  197,    0,
        0,    0,    0,    0,    0,    0,    0,  197,  200,    0,
        0,    0,  200,    0,    0,    0,    0,    0,    0,    0,
        0,  200,  202,    0,    0,    0,  202,    0,    0,  202,

      213,    0,    0,    0,    0,    0,  213,  213,  215,    0,
        0,    0,    0,    0,  215,  215,  217,    0,    0,    0,
        0,  217,    0,  217,  229,    0,    0,    0,    0,    0,
      229,  229,  231,    0,    0,    0,    0,  231,    0,  231,
      233,    0,    0,    0,    0,  233,    0,  233,  234,    0,
        0,    0,  234,    0,    0,    0,    0,    0,    0,    0,
        0,  234,  248,    0,    0,    0,    0,    0,  248,  248,
      258,    0,    0,    0,    0,    0,  258,  258,  260,    0,
        0,    0,    0,    0,  260,  260,  262,    0,    0,    0,
        0,  262,    0,  262,  284,    0,    0,    0,    0,    0,

      284,  284,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "code/game/bg_lex.lex"

#line 706 "code/game/bg_lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE bgLexMorphem*

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

int yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 18 "code/game/bg_lex.lex"

#line 932 "code/game/bg_lex.yy.c"

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 308 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 703 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 19 "code/game/bg_lex.lex"
{
	char *s = yytext; s++;
	yyextra->type = LMT_STRING;
	yytext[strlen(yytext)-1] = '\0';
	yyextra->data.str = yytext + 1;
	yyextra->column += strlen(yytext);
	return LMT_STRING;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 27 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_INT;
	yyextra->data.numInteger = atoi(yytext);
	yyextra->column += strlen(yytext);
	return LMT_INT;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_DOUBLE;
	yyextra->data.numDouble = atof(yytext);
	yyextra->column += strlen(yytext);
	return LMT_DOUBLE;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_SYMBOL;
	yyextra->data.symbol = bgLex_textToSymbol(yytext);
	yyextra->column += strlen(yytext);
	return LMT_SYMBOL;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 58 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 70 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 94 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 106 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 118 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 130 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 142 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 155 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 167 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 179 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 191 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 203 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 215 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 227 "code/game/bg_lex.lex"
{
	double a, b, c;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf }", &a, &b, &c);
	yyextra->data.vector3[0] = a;
	yyextra->data.vector3[1] = b;
	yyextra->data.vector3[2] = c;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR3;
	return LMT_VECTOR3;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 239 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 252 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 265 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 278 "code/game/bg_lex.lex"
{ 
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 291 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 304 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 317 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 330 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 343 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 356 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 369 "code/game/bg_lex.lex"
{ 
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 382 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 395 "code/game/bg_lex.lex"
{ 
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 408 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 421 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 434 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf %lf %lf %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 447 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 460 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 473 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 486 "code/game/bg_lex.lex"
{ 
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 499 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 512 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 525 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 538 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 551 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 564 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 577 "code/game/bg_lex.lex"
{ 
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 590 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 603 "code/game/bg_lex.lex"
{ 
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 616 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 629 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 642 "code/game/bg_lex.lex"
{
	double a, b, c, d;

	// cppcheck-suppress invalidscanf
	sscanf(yytext, "{ %lf, %lf, %lf, %lf }", &a, &b, &c, &d);
	yyextra->data.vector4[0] = a;
	yyextra->data.vector4[1] = b;
	yyextra->data.vector4[2] = c;
	yyextra->data.vector4[3] = d;
	yyextra->column += strlen(yytext);
	yyextra->type = LMT_VECTOR4;
	return LMT_VECTOR4;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 655 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_SYMBOL;
	yyextra->data.symbol = LSYM_OBRACEC;
	yyextra->column++;
	return LMT_SYMBOL;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 661 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_SYMBOL;
	yyextra->data.symbol = LSYM_CBRACEC;
	yyextra->column++;
	return LMT_SYMBOL;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 667 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_SYMBOL;
	yyextra->data.symbol = LSYM_OBRACE;
	yyextra->column++;
	return LMT_SYMBOL;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 673 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_SYMBOL;
	yyextra->data.symbol = LSYM_CBRACE;
	yyextra->column++;
	return LMT_SYMBOL;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 679 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_SYMBOL;
	yyextra->data.symbol = LSYM_OBRACESQ;
	yyextra->column++;
	return LMT_SYMBOL;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 685 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_SYMBOL;
	yyextra->data.symbol = LSYM_CBRACESQ;
	yyextra->column++;
	return LMT_SYMBOL;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 691 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_SYMBOL;
	yyextra->data.symbol = LSYM_SEMICOLON;
	yyextra->column++;
	return LMT_SYMBOL;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 697 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_SYMBOL;
	yyextra->data.symbol = LSYM_POINT;
	yyextra->column += 1;
	return LMT_SYMBOL;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 703 "code/game/bg_lex.lex"
{
	yyextra->column++;
	yyextra->type = LMT_IGNORE;
	return LMT_IGNORE;
}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 708 "code/game/bg_lex.lex"
{
	yyextra->line++;
	yyextra->column = 0;
	yyextra->type = LMT_IGNORE;
	return LMT_IGNORE;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 714 "code/game/bg_lex.lex"
{
	yyextra->type = LMT_EOF;
	return LMT_EOF;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 718 "code/game/bg_lex.lex"
{
	yyextra->column++;
	yyextra->type = LMT_IGNORE;
	return LMT_IGNORE;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 723 "code/game/bg_lex.lex"
ECHO;
	YY_BREAK
#line 1979 "code/game/bg_lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 308 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 308 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 307);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 723 "code/game/bg_lex.lex"



#ifdef LEX_TEXT
int main(int argc, char* argv[]) {
	char buff[4096];
	yyscan_t scanner;
	FILE* f;
	bgLex* lex;

	f = fopen("test.txt", "r");
	fread(buff, 4096, 1, f);
	fclose(f);
  
	lex = bgLex_create(buff);
	while(bgLex_lex(lex)) {
		printf("type=%i symbol=%i yytext=%s\n", lex->morphem.type, lex->morphem.data.symbol, yyget_text(lex->lex));
	}
	bgLex_destroy(lex);

	return EXIT_SUCCESS;
}
#endif

bgLex* bgLex_create(char* data) {
	bgLex* l = malloc(sizeof(bgLex));

	/* HACK: prevent compiler warnings */
	UNUSED(yyunput);
	UNUSED(input);

	if(l != NULL) {
		l->morphem.line = 0;
		l->morphem.column = 0;

		yylex_init_extra(&l->morphem,&l->lex);
		l->buf = yy_scan_string(data,l->lex);
	}

	return l;
}

void bgLex_destroy(bgLex* lex) {
	if(lex == NULL) {
		return;
	}

	if(lex->buf != NULL) {
		yy_delete_buffer(lex->buf,lex->lex);
	}

	if(lex->lex != NULL) {
		yylex_destroy(lex->lex);
	}

	free(lex);
}

int bgLex_lex(bgLex* lex) {
	int res;

	/* skip LMT_IGNORE */
	while(1) {
		res = yylex(lex->lex);
		if(lex->morphem.type != LMT_IGNORE) {
			break;
		}
	}

	return res;
}

bgLexSymbol bgLex_textToSymbol(char* text) {
	if(strcmp("ServerChangeConfig", text) == 0) {
		return LSYM_SERVER_CHANGE_CONFIG;
	}

	if(strcmp("Server", text) == 0) {
		return LSYM_SERVER;
	}

	if(strcmp("HolodeckData", text) == 0) {
		return LSYM_HOLODECK_DATA;
	}

	if(strcmp("Program", text) == 0) {
		return LSYM_PROGRAM;
	}

	if(strcmp("MapChangeConfig", text) == 0) {
		return LSYM_MAP_CHANGE_CONFIG;
	}

	if(strcmp("Map", text) == 0) {
		return LSYM_MAP;
	}

	if(strcmp("LocationsList2", text) == 0) {
		return LSYM_LOCATIONS_LIST_2;
	}

	if(strcmp("LocationsList", text) == 0) {
		return LSYM_LOCATIONS_LIST;
	}

	if(strcmp("message", text) == 0) {
		return LSYM_MESSAGE;
	}

	if(strcmp("consoleName", text) == 0) {
		return LSYM_CONSOLE_NAME;
	}

	if(strcmp("formalName", text) == 0) {
		return LSYM_FORMAL_NAME;
	}

	if(strcmp("radarColor", text) == 0) {
		return LSYM_RADAR_COLOR;
	}

	if(strcmp("iconColor", text) == 0) {
		return LSYM_ICON_COLOR;
	}

	if(strcmp("NULL", text) == 0) {
		return LSYM_NULL;
	}

	if(strcmp("modelSkin", text) == 0) {
		return LSYM_MODEL_SKIN;
	}

	if(strcmp("weapons", text) == 0) {
		return LSYM_WEAPONS;
	}

	if(strcmp("hasRanks", text) == 0) {
		return LSYM_HAS_RANKS;
	}

	if(strcmp("teal", text) == 0) {
		return LSYM_TEAL;
	}

	if(strcmp("medical", text) == 0) {
		return LSYM_MEDICAL;
	}

	if(strcmp("gold", text) == 0) {
		return LSYM_GOLD;
	}

	if(strcmp("green", text) == 0) {
		return LSYM_GREEN;
	}

	if(strcmp("marine", text) == 0) {
		return LSYM_MARINE;
	}

	if(strcmp("red", text) == 0) {
		return LSYM_RED;
	}

	if(strcmp("WP_TRICORDER", text) == 0) {
		return LSYM_WP_TRICORDER;
	}

	if(strcmp("WP_PADD", text) == 0) {
		return LSYM_WP_PADD;
	}

	if(strcmp("WP_COFFEE", text) == 0) {
		return LSYM_WP_COFFEE;
	}

	if(strcmp("WP_PHASER", text) == 0) {
		return LSYM_WP_PHASER;
	}

	if(strcmp("WP_COMPRESSION_RIFLE", text) == 0) {
		return LSYM_WP_COMPRESSION_RIFLE;
	}

	if(strcmp("WP_TR116", text) == 0) {
		return LSYM_WP_TR116;
	}

	if(strcmp("WP_GRENADE_LAUNCHER", text) == 0) {
		return LSYM_WP_GRENADE_LAUNCHER;
	}

	if(strcmp("WP_QUANTUM_BURST", text) == 0) {
		return LSYM_WP_QUANTUM_BURST;
	}

	if(strcmp("WP_MEDKIT", text) == 0) {
		return LSYM_WP_MEDKIT;
	}

	if(strcmp("WP_VOYAGER_HYPO", text) == 0) {
		return LSYM_WP_VOYAGER_HYPO;
	}

	if(strcmp("WP_DERMAL_REGEN", text) == 0) {
		return LSYM_WP_DERMAL_REGEN;
	}

	if(strcmp("WP_TOOLKIT", text) == 0) {
		return LSYM_WP_TOOLKIT;
	}

	if(strcmp("WP_HYPERSPANNER", text) == 0) {
		return LSYM_WP_HYPERSPANNER;
	}

	if(strcmp("WP_DISRUPTOR", text) == 0) {
		return LSYM_WP_DISRUPTOR;
	}

	if(strcmp("WP_NULL", text) == 0) {
		return LSYM_WP_NULL;
	}

	if(strcmp("WP_NULL_HANDS", text) == 0) {
		return LSYM_WP_NULL_HANDS;
	}

	if(strcmp("WP_0", text) == 0) {
		return LSYM_WP_0;
	}

	if(strcmp("WP_1", text) == 0) {
		return LSYM_WP_1;
	}

	if(strcmp("WP_2", text) == 0) {
		return LSYM_WP_2;
	}

	if(strcmp("WP_3", text) == 0) {
		return LSYM_WP_3;
	}

	if(strcmp("WP_4", text) == 0) {
		return LSYM_WP_4;
	}

	if(strcmp("WP_5", text) == 0) {
		return LSYM_WP_5;
	}

	if(strcmp("WP_6", text) == 0) {
		return LSYM_WP_6;
	}

	if(strcmp("WP_7", text) == 0) {
		return LSYM_WP_7;
	}

	if(strcmp("WP_8", text) == 0) {
		return LSYM_WP_8;
	}

	if(strcmp("WP_9", text) == 0) {
		return LSYM_WP_9;
	}

	if(strcmp("WP_10", text) == 0) {
		return LSYM_WP_10;
	}

	if(strcmp("WP_11", text) == 0) {
		return LSYM_WP_11;
	}

	if(strcmp("WP_12", text) == 0) {
		return LSYM_WP_12;
	}

	if(strcmp("WP_13", text) == 0) {
		return LSYM_WP_13;
	}

	if(strcmp("WP_14", text) == 0) {
		return LSYM_WP_14;
	}

	if(strcmp("WP_15", text) == 0) {
		return LSYM_WP_15;
	}

	if(strcmp("admin", text) == 0) {
		return LSYM_ADMIN;
	}

	if(strcmp("borg", text) == 0) {
		return LSYM_BORG;
	}

	if(strcmp("n00b", text) == 0) {
		return LSYM_N00B;
	}

	if(strcmp("noShow", text) == 0) {
		return LSYM_NO_SHOW;
	}

	if(strcmp("MenuTextureDef", text) == 0) {
		return LSYM_MENU_TEXTURE_DEF;
	}

	if(strcmp("ConsoleName", text) == 0) {
		return LSYM_CONSOLE_NAME;
	}

	if(strcmp("FormalName", text) == 0) {
		return LSYM_FORMAL_NAME;
	}

	if(strcmp("MenuTextureRed", text) == 0) {
		return LSYM_MENU_TEXTURE_RED;
	}

	if(strcmp("MenuTextureTeal", text) == 0) {
		return LSYM_MENU_TEXTURE_TEAL;
	}

	if(strcmp("MenuTextureGold", text) == 0) {
		return LSYM_MENU_TEXTURE_GOLD;
	}

	if(strcmp("MenuTextureGreen", text) == 0) {
		return LSYM_MENU_TEXTURE_GREEN;
	}

	if(strcmp("BoltModel", text) == 0) {
		return LSYM_BOLT_MODEL;
	}

	if(strcmp("BoltShader", text) == 0) {
		return LSYM_BOLT_SHADER;
	}

	if(strcmp("AdmiralRank", text) == 0) {
		return LSYM_ADMIRAL_RANK;
	}

	if(strcmp("true", text) == 0) {
		return LSYM_TRUE;
	}

	if(strcmp("false", text) == 0) {
		return LSYM_FALSE;
	}

	if(strcmp("phaser", text) == 0) {
		return LSYM_WCONF_PHASER;
	}

	if(strcmp("crifle", text) == 0) {
		return LSYM_WCONF_CRIFLE;
	}

	if(strcmp("disruptor", text) == 0) {
		return LSYM_WCONF_DISRUPTOR;
	}

	if(strcmp("grenade", text) == 0) {
		return LSYM_WCONF_GRENADE;
	}

	if(strcmp("tr116", text) == 0) {
		return LSYM_WCONF_TR116;
	}

	if(strcmp("quantum", text) == 0) {
		return LSYM_WCONF_QUANTUM;
	}

	if(strcmp("hyperspanner", text) == 0) {
		return LSYM_WCONF_HYPERSPANNER;
	}

	if(strcmp("damage", text) == 0) {
		return LSYM_WCONF_DAMAGE;
	}

	if(strcmp("range", text) == 0) {
		return LSYM_WCONF_RANGE;
	}

	if(strcmp("variation", text) == 0) {
		return LSYM_WCONF_VARIATION;
	}

	if(strcmp("radius", text) == 0) {
		return LSYM_WCONF_RADIUS;
	}

	if(strcmp("size", text) == 0) {
		return LSYM_WCONF_SIZE;
	}

	if(strcmp("time", text) == 0) {
		return LSYM_WCONF_TIME;
	}

	if(strcmp("velocity", text) == 0) {
		return LSYM_WCONF_VELOCITY;
	}

	if(strcmp("splash", text) == 0) {
		return LSYM_WCONF_SPLASH;
	}

	if(strcmp("rate", text) == 0) {
		return LSYM_WCONF_RATE;
	}

	if(strcmp("think", text) == 0) {
		return LSYM_WCONF_THINK;
	}

	if(strcmp("distance", text) == 0) {
		return LSYM_WCONF_DISTANCE;
	}

	return LSYM_UNKNOWN;
}

void bgLexFatalError(const char* msg, void* lex) {
	Com_Printf("LEXER ERROR: %s\n", msg);
}


