// Copyright (C) 1999-2000 Id Software, Inc.
//


#define INVENTORY_NONE				0

//armor
#define INVENTORY_ARMOR				1

//weapons

#define INVENTORY_GRENADELAUNCHER	2
#define INVENTORY_STASIS			3
#define INVENTORY_PHASER			4
#define INVENTORY_DREADNOUGHT		5
#define INVENTORY_IMOD				6
#define INVENTORY_COMPRESSION		7
#define INVENTORY_TETRION			8
#define INVENTORY_SCAVENGER			9
#define INVENTORY_QUANTUM			10

//ammo

#define INVENTORY_GRENADES			11
#define INVENTORY_STASISAMMO		12
#define INVENTORY_PHASERAMMO		13  //!< not a pickup but perhaps useful for bots
#define INVENTORY_DREADNOUGHTAMMO	14
#define INVENTORY_IMODAMMO			15
#define INVENTORY_COMPRESSIONAMMO	16
#define INVENTORY_TETRIONAMMO		17
#define INVENTORY_SCAVENGERAMMO		18
#define INVENTORY_QUANTUMAMMO		19

//powerups
#define INVENTORY_HEALTH			24
#define INVENTORY_TRANSPORTER		25
#define INVENTORY_MEDKIT			26
#define INVENTORY_QUAD				27
#define INVENTORY_ENVIRONMENTSUIT	28
#define INVENTORY_HASTE				29
#define INVENTORY_INVISIBILITY		30
#define INVENTORY_REGEN				31
#define INVENTORY_FLIGHT			32
#define INVENTORY_REDFLAG			33
#define INVENTORY_BLUEFLAG			34
#define INVENTORY_DETPACK			35
#define INVENTORY_SEEKER			36
#define INVENTORY_SHIELD			37
#define INVENTORY_DECOY				38 //!< decoy temp
#define INVENTORY_DETPACK_PLACED	39

#define INVENTORY_HYPO				40
#define INVENTORY_ASSIMILATOR		41
#define INVENTORY_BORG_WEAPON		42

//enemy stuff
#define ENEMY_HORIZONTAL_DIST		200
#define ENEMY_HEIGHT				201
#define NUM_VISIBLE_ENEMIES			202
#define NUM_VISIBLE_TEAMMATES		203

//item numbers (make sure they are in sync with bg_itemlist in bg_misc.c)
// ALSO: make sure this list is the same as the one in \botfiles\inv.h

#define MODELINDEX_NONE				0

#define MODELINDEX_PHASER			1
#define MODELINDEX_COMPRESSION		2
#define MODELINDEX_IMOD				3
#define MODELINDEX_SCAVENGER		4
#define MODELINDEX_STASISWEAPON		5
#define MODELINDEX_GRENADELAUNCHER	6
#define MODELINDEX_TETRION			7
#define MODELINDEX_QUANTUM			8
#define MODELINDEX_DREADNOUGHT		9

#define MODELINDEX_COMPRESSIONAMMO	10
#define MODELINDEX_IMODAMMO			11
#define MODELINDEX_SCAVAMMO			12
#define MODELINDEX_STASISAMMO		13
#define MODELINDEX_GRENADES			14
#define MODELINDEX_TETRIONAMMO		15
#define MODELINDEX_QUANTUMAMMO		16
#define MODELINDEX_DREADNOUGHTAMMO	17

#define MODELINDEX_ARMORSHARD		18
#define MODELINDEX_ARMORCOMBAT		19
#define MODELINDEX_ARMORBODY		20
#define MODELINDEX_HEALTHSMALL		21
#define MODELINDEX_HEALTH			22

#define MODELINDEX_TELEPORTER		23
#define MODELINDEX_MEDKIT			24
#define MODELINDEX_QUAD				25
#define MODELINDEX_ENVIRONMENTSUIT	26
#define MODELINDEX_HASTE			27
#define MODELINDEX_INVISIBILITY		28
#define MODELINDEX_REGEN			29
#define MODELINDEX_FLIGHT			30
#define MODELINDEX_REDFLAG			31
#define MODELINDEX_BLUEFLAG			32
#define MODELINDEX_DETPACK			33
#define MODELINDEX_SEEKER			34
#define MODELINDEX_SHIELD			35
#define MODELINDEX_DECOY			36	//!< decoy temp

#define MODELINDEX_HYPO				37
#define MODELINDEX_ASSIMILATOR		38
#define MODELINDEX_BORG_WEAPON		39
