// Copyright (C) 1999-2000 Id Software, Inc.
//

#ifndef INV_H_
#define INV_H_

enum inventory_e {
	INVENTORY_NONE,

	//armor
	INVENTORY_ARMOR,

	//weapons

	INVENTORY_GRENADELAUNCHER,
	INVENTORY_STASIS,
	INVENTORY_PHASER,
	INVENTORY_DREADNOUGHT,
	INVENTORY_IMOD,
	INVENTORY_COMPRESSION,
	INVENTORY_TETRION,
	INVENTORY_SCAVENGER,
	INVENTORY_QUANTUM,

	//ammo

	INVENTORY_GRENADES,
	INVENTORY_STASISAMMO,
	INVENTORY_PHASERAMMO, //!< not a pickup but perhaps useful for bots
	INVENTORY_DREADNOUGHTAMMO,
	INVENTORY_IMODAMMO,
	INVENTORY_COMPRESSIONAMMO,
	INVENTORY_TETRIONAMMO,
	INVENTORY_SCAVENGERAMMO,
	INVENTORY_QUANTUMAMMO,

	//powerups
	INVENTORY_HEALTH = 24,
	INVENTORY_TRANSPORTER,
	INVENTORY_MEDKIT,
	INVENTORY_QUAD,
	INVENTORY_ENVIRONMENTSUIT,
	INVENTORY_HASTE,
	INVENTORY_INVISIBILITY,
	INVENTORY_REGEN,
	INVENTORY_FLIGHT,
	INVENTORY_REDFLAG,
	INVENTORY_BLUEFLAG,
	INVENTORY_DETPACK,
	INVENTORY_SEEKER,
	INVENTORY_SHIELD,
	INVENTORY_DECOY, //!< decoy temp
	INVENTORY_DETPACK_PLACED,

	INVENTORY_HYPO,
	INVENTORY_ASSIMILATOR,
	INVENTORY_BORG_WEAPON,

	//enemy stuff
	ENEMY_HORIZONTAL_DIST = 200,
	ENEMY_HEIGHT,
	NUM_VISIBLE_ENEMIES,
	NUM_VISIBLE_TEAMMATES
};

//item numbers (make sure they are in sync with bg_itemlist in bg_misc.c)
// ALSO: make sure this list is the same as the one in \botfiles\inv.h

enum modelIndices_e {
	MODELINDEX_NONE,

	MODELINDEX_PHASER,
	MODELINDEX_COMPRESSION,
	MODELINDEX_IMOD,
	MODELINDEX_SCAVENGER,
	MODELINDEX_STASISWEAPON,
	MODELINDEX_GRENADELAUNCHER,
	MODELINDEX_TETRION,
	MODELINDEX_QUANTUM,
	MODELINDEX_DREADNOUGHT,

	MODELINDEX_COMPRESSIONAMMO,
	MODELINDEX_IMODAMMO,
	MODELINDEX_SCAVAMMO,
	MODELINDEX_STASISAMMO,
	MODELINDEX_GRENADES,
	MODELINDEX_TETRIONAMMO,
	MODELINDEX_QUANTUMAMMO,
	MODELINDEX_DREADNOUGHTAMMO,

	MODELINDEX_ARMORSHARD,
	MODELINDEX_ARMORCOMBAT,
	MODELINDEX_ARMORBODY,
	MODELINDEX_HEALTHSMALL,
	MODELINDEX_HEALTH,

	MODELINDEX_TELEPORTER,
	MODELINDEX_MEDKIT,
	MODELINDEX_QUAD,
	MODELINDEX_ENVIRONMENTSUIT,
	MODELINDEX_HASTE,
	MODELINDEX_INVISIBILITY,
	MODELINDEX_REGEN,
	MODELINDEX_FLIGHT,
	MODELINDEX_REDFLAG,
	MODELINDEX_BLUEFLAG,
	MODELINDEX_DETPACK,
	MODELINDEX_SEEKER,
	MODELINDEX_SHIELD,
	MODELINDEX_DECOY,	//!< decoy temp

	MODELINDEX_HYPO,
	MODELINDEX_ASSIMILATOR,
	MODELINDEX_BORG_WEAPON
};


#endif /* INV_H_ */
